POST https://node-clec.onrender.com/videos
Content-Type: application/json

{
    "title": "Outro Video de node",
    "description": "Esse é o video mais novo",
    "duration": 180
}

### 

GET https://node-clec.onrender.com/videos

###

PUT https://node-clec.onrender.com/videos/
Content-Type: application/json

{
    "title": "Video node alterado",
    "description": "Esse é o primeiro video node alterado",
    "duration": 180
}

###

DELETE https://node-clec.onrender.com/videos/
###